pub fn suffix(path: &str) -> Option<&'static str> {
    let suffix = match path {
        "core::cell::Cell" => "cell/Cell#",
        "core::cell::Cell::get" => "cell/impl#[`Cell<T>`]get().",
        "core::cell::Cell::new" => "cell/impl#[`Cell<T>`]new().",
        "core::cell::Cell::set" => "cell/impl#[`Cell<T>`]set().",
        "core::iter::Iterator::enumerate" => "iter/traits/iterator/Iterator#enumerate().",
        "core::macros::assert_eq" => "macros/assert_eq!",
        "core::mem::drop" => "mem/drop().",
        "core::num::rotate_right" => "]rotate_right().",
        "core::num::wrapping_add" => "]wrapping_add().",
        "core::num::wrapping_mul" => "]wrapping_mul().",
        "core::num::wrapping_shl" => "]wrapping_shl().",
        "core::num::wrapping_sub" => "]wrapping_sub().",
        "core::ops::drop::Drop" => "ops/drop/Drop#",
        "core::option::Option" => "option/Option#",
        "core::option::Option::None" => "option/Option#None#",
        "core::option::Option::Some" => "option/Option#Some#",
        "core::option::Option::unwrap" => "option/impl#[`Option<T>`]unwrap().",
        "core::option::branch" => "option/impl#[`Option<T>`][Try]branch().",
        "core::result::Result" => "result/Result#",
        "core::result::Result::Err" => "result/Result#Err#",
        "core::result::Result::Ok" => "result/Result#Ok#",
        "core::result::Result::unwrap" => "result/impl#[`Result<T, E>`]unwrap().",
        "core::result::branch" => "result/impl#[`Result<T, E>`][Try]branch().",
        "core::slice::iter" => "slice/impl#[`[T]`]iter().",
        "core::slice::len" => "slice/impl#[`[T]`]len().",
        "core::str::as_bytes" => "str/impl#[str]as_bytes().",
        "std::iter::zip" => "iter/adapters/zip/zip().",
        "std::macros::assert" => "macros/builtin/assert!",
        "std::macros::panic" => "macros/panic!",
        "std::macros::println" => "macros/println!",
        _ => return None,
    };
    Some(suffix)
}
